site_name: Let's Go! Golang 短视频教程
site_author: 'PegasusWang'
repo_name: 'LetsGo'
repo_url: 'https://github.com/PegasusWang/LetsGo'
# theme: readthedocs

copyright: 'Copyright &copy; 2019 - 2020 PegasusWang'

# Configuration, https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  # disqus: 'pegasus'
  social:
    - type: 'github'
      link: 'https://github.com/PegasusWang'

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: true  #for use of inline $..$
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.superfences

nav:
- 简介: 'index.md'
- Go基础:
  - 'Hello Go!': 'basics/00_hello_go/hello_go.md'
  - 'Go 基础类型': 'basics/01_go_basic_types/basic_types.md'
  - 'Go 数组和切片': 'basics/02_go_array_and_slice/array_and_slice.md'
  - 'Go 映射': 'basics/03_map/map.md'
  - 'Go 控制流语句': 'basics/04_go_control_flow/go_procedural.md'
  - 'Go 函数': 'basics/05_func/func.md'
  - 'Go 错误处理': 'basics/06_error/error.md'
