site_name: Let's Go! Golang 短视频教程
site_author: 'PegasusWang'
# theme: readthedocs

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 PegasusWang'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/PegasusWang'

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$
  - codehilite:
      guess_lang: False
  - toc:
      permalink: true

nav:
- 简介: 'index.md'
- Go基础:
  - 'Hello Go!': 'basics/00_hello_go/hello_go.md'
  - 'Go 基础类型': 'basics/01_go_basic_types/basic_types.md'
  - 'Go 数组和切片': 'basics/02_go_array_and_slice/array_and_slice.md'
  - 'Go 映射': 'basics/03_map/map.md'
  - 'Go 控制流语句': 'basics/04_go_control_flow/go_procedural.md'
  - 'Go 函数': 'basics/05_func/func.md'
  - 'Go 错误处理': 'basics/06_error/error.md'
